# Generated by Django 3.1.1 on 2020-09-17 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('friendliness', models.IntegerField(max_length=1)),
                ('trainability', models.IntegerField(max_length=1)),
                ('sheddingamount', models.IntegerField(max_length=1)),
                ('exerciseneeds', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=2)),
                ('gender', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('favouritefood', models.CharField(max_length=100)),
                ('favouritetoy', models.CharField(max_length=100)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.breed')),
            ],
        ),
    ]
