# Generated by Django 3.1.1 on 2020-09-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='exerciseneeds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='breed',
            name='friendliness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='breed',
            name='sheddingamount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='breed',
            name='trainability',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='age',
            field=models.IntegerField(),
        ),
    ]
