# Generated by Django 3.1.1 on 2020-09-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_auto_20200920_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
    ]
