# This is a basic workflow to help you get started with Actions

name: Django Server Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.8']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}}
      - name: Installing Pipenv
        run: |
          python -m pip install --upgrade pip
          sudo pip install pipenv
      - name: Installing Requirements from pipfile
        run: |
          pipenv install

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pipenv run python manage.py check
          pipenv run python manage.py migrate
          pipenv run python manage.py test
